language: groovy

cache:
    directories:
        - $HOME/.m2
        - $HOME/.grails
        - $HOME/.gradle
        - $HOME/.npm

jobs:
    include:
        - &backend-prepare
          stage: Compilation
          jdk: oraclejdk8
          before_script: 
              - cd backend 
              - chmod +x ./grailsw 
              - chmod +x ./gradlew 
          script: ./grailsw compile
        - &frontend-prepare
          stage: Compilation
          node_js:
              - 6
          before_script:
              - cd frontend
              - npm install
          script: npm run build --prod
        - <<: *backend-prepare
          stage: Static code analysis
          script: ./gradlew codenarcMain 
        - <<: *backend-prepare
          stage: Static code analysis 
          script: ./gradlew codenarcTest
        - <<: *frontend-prepare
          stage: Static code analysis
          script: npm run lint
        - <<: *backend-prepare
          stage: Unit tests
          script: ./gradlew test --stacktrace
        - <<: *frontend-prepare
          stage: Unit tests
          script: npm run test
