language: groovy

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
    directories:
        - $HOME/.m2
        - $HOME/.grails
        - $HOME/.gradle
        - $HOME/.npm

jobs:
    include:
        - &backend-prepare
          stage: Compilation
          env: DESC=backend
          jdk: oraclejdk8
          before_script: 
              - cd backend 
              - chmod +x ./grailsw 
              - chmod +x ./gradlew 
          script: ./grailsw compile
        - &frontend-prepare
          stage: Compilation
          env: DESC=frontend
          node_js:
              - 6
          before_script:
              - "sudo chown root /opt/google/chrome/chrome-sandbox"
              - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
              - cd frontend
              - npm install
          script: npm run build --prod
        - <<: *backend-prepare
          env: DESC=backend-main
          stage: Static code analysis
          script: ./gradlew codenarcMain 
        - <<: *backend-prepare
          env: DESC=backend-test
          stage: Static code analysis 
          script: ./gradlew codenarcTest
        - <<: *frontend-prepare
          env: DESC=frontend
          stage: Static code analysis
          script: npm run lint
        - <<: *backend-prepare
          env: DESC=backend
          stage: Unit tests
          script: ./gradlew test --stacktrace
        - <<: *frontend-prepare
          env: DESC=frontend
          stage: Unit tests
          script: npm run ci
