language: groovy
        
jdk:
    - oraclejdk8

jobs:
    include:
        - stage: Preparation
          script: cd shortcuts-backend && chmod +x ./grailsw && chmod +x ./gradlew
        - stage: Compilation
          script: cd shortcuts-backend && ./grailsw compile
        - stage: Unit tests
          script: cd shortcuts-backend && ./grailsw test-app --non-interactive --echoOut --stacktrace
        - stage: Package
          script: cd shortcuts-backend && ./grailsw war
