language: groovy
        
jdk:
    - oraclejdk8

jobs:
    include:
        - stage: Preparation
          script: cd shortcuts-backend 
          script: chmod +x ./grailsw
          script: chmod +x ./gradlew
        - stage: Compilation
          script: cd shortcuts-backend 
          script: ./grailsw compile
        - stage: Unit tests
          script: cd shortcuts-backend 
          script: ./grailsw test-app --non-interactive --echoOut --stacktrace
        - stage: Package
          script: cd shortcuts-backend 
          script: ./grailsw war
