language: groovy

cache:
    directories:
        - $HOME/.m2
        - $HOME/.grails
        - $HOME/.gradle

jobs:
    include:
        - &backend-prepare
          stage: Compilation
          jdk: oraclejdk8
          before_script: 
              - cd backend 
              - chmod +x ./grailsw 
              - chmod +x ./gradlew 
          script: ./grailsw compile
        - <<: *backend-prepare
          stage: Unit tests
          script: ./grailsw test-app --non-interactive --echoOut --stacktrace
