language: groovy

jobs:
    jdk:
        - oraclejdk8
    include:
        - stage: Preparation
          script:
              cd shortcuts-backend 
              chmod +x grailsw
              chmod +x gradlew
        - stage: Compilation
          script: ./grailsw compile
        - stage: Unit tests
          script: ./grailsw test-app --non-interactive --echoOut --stacktrace
        - stage: Package
          script: ./grailsw war