language: groovy

cache:
    directories:
        - $HOME/.m2
        - $HOME/.grails
        - $HOME/.gradle

jobs:
    include:
        - &backend-prepare
          stage: Compilation
          jdk: oraclejdk8
          before_script: 
              - cd shortcuts-backend 
              - chmod +x ./grailsw 
              - chmod +x ./gradlew 
          script: ./grailsw compile
        - <<: *backend-prepare
          stage: Static code analysis
          script: ./gradlew codenarcMain 
        - <<: *backend-prepare
          script: ./gradlew codenarcTest
        - <<: *backend-prepare
          stage: Unit tests
          script: ./gradlew test --stacktrace
