language: groovy

jdk:
    - oraclejdk8

before_script:
    - cd shortcuts-backend 
    - chmod +x grailsw

jobs:
    include:
        - stage: Compilation
          script: ./grailsw compile
        - stage: Unit tests
          script: ./grailsw test-app --non-interactive --echoOut --stacktrace
        - stage: Package
          script: ./grails war