language: groovy

cache:
    directories:
        - $HOME/.m2
        - $HOME/.grails
        - $HOME/.gradle

jobs:
    include:
        - &backend-prepare
          stage: Backend - Compilation
          jdk: oraclejdk8
          before_script: 
              - cd backend 
              - chmod +x ./grailsw 
              - chmod +x ./gradlew 
          script: ./grailsw compile
        - <<: *backend-prepare
          stage: Backend - Static code analysis (Production)
          script: ./gradlew codenarcMain 
        - <<: *backend-prepare
          stage: Backend - Static code analysis (Test)
          script: ./gradlew codenarcTest
        - <<: *backend-prepare
          stage: Backend - Unit tests
          script: ./gradlew test --stacktrace
        - stage: Frontend - Static code analysis
          script: npm run lint
