language: groovy

cache:
  directories:
      - $HOME/.m2

jobs:
    include:
        - stage: Compilation
          script: cd shortcuts-backend && chmod +x ./grailsw && chmod +x ./gradlew && ./grailsw compile
          jdk: oraclejdk8
        - stage: Unit tests
          script: cd shortcuts-backend && chmod +x ./grailsw && chmod +x ./gradlew && ./grailsw test-app --non-interactive --echoOut --stacktrace
          jdk: oraclejdk8
